test

diff --git a/Ferryx-Worker/Dockerfile b/Ferryx-Worker/Dockerfile
--- a/Ferryx-Worker/Dockerfile
+++ b/Ferryx-Worker/Dockerfile
@@ -1,14 +1,12 @@
-# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.
-
-# This stage is used when running from VS in fast mode (Default for Debug configuration)
+# Base runtime
 FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
 USER $APP_UID
 WORKDIR /app
-EXPOSE 8080
-EXPOSE 8081
 
+# Uygulama portu (yüksek port)
+EXPOSE 16080
 
-# This stage is used to build the service project
+# Build
 FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
 ARG BUILD_CONFIGURATION=Release
 WORKDIR /src
@@ -18,13 +16,23 @@ COPY . .
 WORKDIR "/src/Ferryx-Worker"
 RUN dotnet build "./Ferryx-Worker.csproj" -c $BUILD_CONFIGURATION -o /app/build
 
-# This stage is used to publish the service project to be copied to the final stage
+# Publish
 FROM build AS publish
 ARG BUILD_CONFIGURATION=Release
 RUN dotnet publish "./Ferryx-Worker.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false
 
-# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
+# Final
 FROM base AS final
 WORKDIR /app
 COPY --from=publish /app/publish .
-ENTRYPOINT ["dotnet", "Ferryx-Worker.dll"]
+
+# Kestrel portunu sabitle (istersen deðiþtirebilirsin)
+ENV ASPNETCORE_URLS=http://0.0.0.0:16080
+
+# Zorunlu env kontrol + start
+ENTRYPOINT ["/bin/sh","-c", "\
+  test -n \"$FERRYX_HUB_TOKEN\" || (echo 'FERRYX_HUB_TOKEN is required' && exit 1); \
+  test -n \"$FERRYX_GROUP\" || (echo 'FERRYX_GROUP is required' && exit 1); \
+  test -n \"$FERRYX_HUB_URL\" || (echo 'FERRYX_HUB_URL is required' && exit 1); \
+  exec dotnet Ferryx-Worker.dll \
+"]
